// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package hall

import (
	"reflect"

	"fmt"
)

type RoomInst struct {
	Roomproxy string `sproto:"string,0,name=Roomproxy"`

	Player_num int `sproto:"integer,1,name=Player_num"`

	Player_limit int `sproto:"integer,2,name=Player_limit"`

	Server_id int `sproto:"integer,3,name=Server_id"`

	Game_id int `sproto:"integer,5,name=Game_id"`

	Room_type int `sproto:"integer,6,name=Room_type"`

	Room_name string `sproto:"string,7,name=Room_name"`

	Init_bet int `sproto:"integer,8,name=Init_bet"`

	Min_enter int `sproto:"integer,9,name=Min_enter"`

	Group_type int `sproto:"integer,10,name=Group_type"`

	Min_group_player int `sproto:"integer,11,name=Min_group_player"`

	Max_group_player int `sproto:"integer,12,name=Max_group_player"`
}

func (self *RoomInst) String() string { return fmt.Sprintf("%+v", *self) }

type RoomListReq struct {
	Game_id []int `sproto:"integer,0,array,name=Game_id"`
}

func (self *RoomListReq) String() string { return fmt.Sprintf("%+v", *self) }

type RoomInstList struct {
	Room_insts []*RoomInst `sproto:"struct,0,array,name=Room_insts"`
}

func (self *RoomInstList) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerOnlineState struct {
	Room_id int `sproto:"integer,0,name=Room_id"`

	Roomproxy string `sproto:"string,1,name=Roomproxy"`
}

func (self *PlayerOnlineState) String() string { return fmt.Sprintf("%+v", *self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*RoomInst)(nil)).Elem(),          // 264720722
	reflect.TypeOf((*RoomListReq)(nil)).Elem(),       // 2037445754
	reflect.TypeOf((*RoomInstList)(nil)).Elem(),      // 2595728295
	reflect.TypeOf((*PlayerOnlineState)(nil)).Elem(), // 701486018
}

var SProtoEnumValue = map[string]map[int32]string{}
