// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package auth

import (
	"reflect"

	"fmt"
)

type BalanceInfo struct {
	Type int `sproto:"integer,0,name=Type"`

	Last_operate_time string `sproto:"string,1,name=Last_operate_time"`

	Balance int `sproto:"integer,2,name=Balance"`

	Player_id int `sproto:"integer,3,name=Player_id"`

	Sid int `sproto:"integer,4,name=Sid"`
}

func (self *BalanceInfo) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerInfo struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Player_id int `sproto:"integer,1,name=Player_id"`

	Nickname string `sproto:"string,2,name=Nickname"`

	Head_id int `sproto:"integer,3,name=Head_id"`

	Head_url string `sproto:"string,4,name=Head_url"`

	Sex int `sproto:"integer,5,name=Sex"`

	Balance_total int `sproto:"integer,6,name=Balance_total"`

	Balance []*BalanceInfo `sproto:"struct,7,array,name=Balance"`

	Avatar int `sproto:"integer,8,name=Avatar"`

	Fb_avatar string `sproto:"string,9,name=Fb_avatar"`
}

func (self *PlayerInfo) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerBase struct {
	Player_id int `sproto:"integer,0,name=Player_id"`

	Nickname string `sproto:"string,1,name=Nickname"`

	Head_id int `sproto:"integer,2,name=Head_id"`

	Head_url string `sproto:"string,3,name=Head_url"`

	Sex int `sproto:"integer,4,name=Sex"`

	Create_time int `sproto:"integer,5,name=Create_time"`

	Last_mod_time int `sproto:"integer,6,name=Last_mod_time"`

	Balance []*BalanceInfo `sproto:"struct,7,array,name=Balance"`

	Balance_total int `sproto:"integer,8,name=Balance_total"`
}

func (self *PlayerBase) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerLoginReq struct {
	Token string `sproto:"string,0,name=Token"`
}

func (self *PlayerLoginReq) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerLoginReply struct {
	Player *PlayerBase `sproto:"struct,0,name=Player"`

	Token string `sproto:"string,1,name=Token"`

	Is_logined_game bool `sproto:"boolean,2,name=Is_logined_game"`

	Game_ids []int `sproto:"integer,3,array,name=Game_ids"`
}

func (self *PlayerLoginReply) String() string { return fmt.Sprintf("%+v", *self) }

type ServerTimeReply struct {
	Timestamp int `sproto:"integer,0,name=Timestamp"`
}

func (self *ServerTimeReply) String() string { return fmt.Sprintf("%+v", *self) }

type KickPlayer struct {
	Type int `sproto:"integer,0,name=Type"`

	Player_id int `sproto:"integer,1,name=Player_id"`
}

func (self *KickPlayer) String() string { return fmt.Sprintf("%+v", *self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*BalanceInfo)(nil)).Elem(),      // 2720744757
	reflect.TypeOf((*PlayerInfo)(nil)).Elem(),       // 329267527
	reflect.TypeOf((*PlayerBase)(nil)).Elem(),       // 1482456304
	reflect.TypeOf((*PlayerLoginReq)(nil)).Elem(),   // 3606583565
	reflect.TypeOf((*PlayerLoginReply)(nil)).Elem(), // 2192454765
	reflect.TypeOf((*ServerTimeReply)(nil)).Elem(),  // 1090202644
	reflect.TypeOf((*KickPlayer)(nil)).Elem(),       // 343667092
}

var SProtoEnumValue = map[string]map[int32]string{}
