sprotogen --go_out=auth/auth.go --package=auth sp/auth.sproto
sprotogen --go_out=desk/desk.go --package=desk sp/desk.sproto
sprotogen --go_out=gate/gate.go --package=gate sp/gate.sproto
sprotogen --go_out=hall/hall.go --package=hall sp/hall.sproto
sprotogen --go_out=header/header.go --package=header sp/package.sproto
sprotogen --go_out=player/player.go --package=player sp/player.sproto
sprotogen --go_out=room/room.go --package=room sp/room.sproto
sprotogen --go_out=rummy/rummy.go --package=rummy sp/rummy.sproto
sprotogen --go_out=teenpatti/teenpatti.go --package=teenpatti sp/teenpatti.sproto