// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package rummy

import (
	"reflect"

	"fmt"
)

type BalanceInfo struct {
	Type int `sproto:"integer,0,name=Type"`

	Last_operate_time string `sproto:"string,1,name=Last_operate_time"`

	Balance int `sproto:"integer,2,name=Balance"`

	Player_id int `sproto:"integer,3,name=Player_id"`

	Sid int `sproto:"integer,4,name=Sid"`
}

func (self *BalanceInfo) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerInfo struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Player_id int `sproto:"integer,1,name=Player_id"`

	Nickname string `sproto:"string,2,name=Nickname"`

	Head_id int `sproto:"integer,3,name=Head_id"`

	Head_url string `sproto:"string,4,name=Head_url"`

	Sex int `sproto:"integer,5,name=Sex"`

	Balance_total int `sproto:"integer,6,name=Balance_total"`

	Balance []*BalanceInfo `sproto:"struct,7,array,name=Balance"`

	Avatar int `sproto:"integer,8,name=Avatar"`

	Fb_avatar string `sproto:"string,9,name=Fb_avatar"`
}

func (self *PlayerInfo) String() string { return fmt.Sprintf("%+v", *self) }

type SeatState struct {
	Seat int `sproto:"integer,0,name=Seat"`

	State int `sproto:"integer,1,name=State"`
}

func (self *SeatState) String() string { return fmt.Sprintf("%+v", *self) }

type CardsGroup struct {
	Type int `sproto:"integer,0,name=Type"`

	Cards []int `sproto:"integer,1,array,name=Cards"`
}

func (self *CardsGroup) String() string { return fmt.Sprintf("%+v", *self) }

type SeatCards struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Cardinfo []*CardsGroup `sproto:"struct,1,array,name=Cardinfo"`

	Scores int `sproto:"integer,2,name=Scores"`

	Cards []int `sproto:"integer,3,array,name=Cards"`

	Player_info *PlayerInfo `sproto:"struct,4,name=Player_info"`
}

func (self *SeatCards) String() string { return fmt.Sprintf("%+v", *self) }

type Winlost struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Winlost int `sproto:"integer,1,name=Winlost"`

	Fee int `sproto:"integer,2,name=Fee"`

	Player_id int `sproto:"integer,3,name=Player_id"`
}

func (self *Winlost) String() string { return fmt.Sprintf("%+v", *self) }

type TableBase struct {
	Deal_id int `sproto:"integer,0,name=Deal_id"`

	Game_state int `sproto:"integer,1,name=Game_state"`
}

func (self *TableBase) String() string { return fmt.Sprintf("%+v", *self) }

type Table struct {
	Table_base *TableBase `sproto:"struct,0,name=Table_base"`

	Player_map []*PlayerInfo `sproto:"struct,1,array,name=Player_map"`

	Seat_state_map []*SeatState `sproto:"struct,2,array,name=Seat_state_map"`

	Player_cards_map []*SeatCards `sproto:"struct,3,array,name=Player_cards_map"`

	Winlost_map []*Winlost `sproto:"struct,4,array,name=Winlost_map"`
}

func (self *Table) String() string { return fmt.Sprintf("%+v", *self) }

type QryDeskReq struct {
}

func (self *QryDeskReq) String() string { return fmt.Sprintf("%+v", *self) }

type QryDeskReply struct {
	Table_info *Table `sproto:"struct,0,name=Table_info"`
}

func (self *QryDeskReply) String() string { return fmt.Sprintf("%+v", *self) }

type DrawReq struct {
	Draw_type int `sproto:"integer,0,name=Draw_type"`

	Seat int `sproto:"integer,1,name=Seat"`

	Player_id int `sproto:"integer,2,name=Player_id"`
}

func (self *DrawReq) String() string { return fmt.Sprintf("%+v", *self) }

type DrawReply struct {
	Card int `sproto:"integer,0,name=Card"`

	Cards_info *SeatCards `sproto:"struct,1,name=Cards_info"`
}

func (self *DrawReply) String() string { return fmt.Sprintf("%+v", *self) }

type DiscardReq struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Player_id int `sproto:"integer,1,name=Player_id"`

	Discard_card int `sproto:"integer,2,name=Discard_card"`
}

func (self *DiscardReq) String() string { return fmt.Sprintf("%+v", *self) }

type DiscardReply struct {
	Cards_info *SeatCards `sproto:"struct,0,name=Cards_info"`
}

func (self *DiscardReply) String() string { return fmt.Sprintf("%+v", *self) }

type WinReq struct {
	Cards_info *SeatCards `sproto:"struct,0,name=Cards_info"`

	Wincard int `sproto:"integer,1,name=Wincard"`
}

func (self *WinReq) String() string { return fmt.Sprintf("%+v", *self) }

type WinReply struct {
	Result int `sproto:"integer,0,name=Result"`
}

func (self *WinReply) String() string { return fmt.Sprintf("%+v", *self) }

type DeclareReq struct {
	Cards_info *SeatCards `sproto:"struct,0,name=Cards_info"`
}

func (self *DeclareReq) String() string { return fmt.Sprintf("%+v", *self) }

type DeclareReply struct {
	Result int `sproto:"integer,0,name=Result"`
}

func (self *DeclareReply) String() string { return fmt.Sprintf("%+v", *self) }

type DropReq struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Player_id int `sproto:"integer,1,name=Player_id"`
}

func (self *DropReq) String() string { return fmt.Sprintf("%+v", *self) }

type DropReply struct {
	Winlost int `sproto:"integer,0,name=Winlost"`

	Player_info *PlayerInfo `sproto:"struct,1,name=Player_info"`
}

func (self *DropReply) String() string { return fmt.Sprintf("%+v", *self) }

type DealInfo struct {
	Table_info *Table `sproto:"struct,0,name=Table_info"`
}

func (self *DealInfo) String() string { return fmt.Sprintf("%+v", *self) }

type GameEndEvent struct {
	Player_map []*PlayerInfo `sproto:"struct,0,array,name=Player_map"`

	Seat_state_map []*SeatState `sproto:"struct,1,array,name=Seat_state_map"`

	Player_cards_map []*SeatCards `sproto:"struct,2,array,name=Player_cards_map"`

	Winlost_map []*Winlost `sproto:"struct,3,array,name=Winlost_map"`

	General_card int `sproto:"integer,4,name=General_card"`
}

func (self *GameEndEvent) String() string { return fmt.Sprintf("%+v", *self) }

type UsedCardInfo struct {
	Player_id int `sproto:"integer,0,name=Player_id"`

	Card int `sproto:"integer,1,name=Card"`
}

func (self *UsedCardInfo) String() string { return fmt.Sprintf("%+v", *self) }

type Seat_Type struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Type int `sproto:"integer,1,name=Type"`
}

func (self *Seat_Type) String() string { return fmt.Sprintf("%+v", *self) }

type SeatStateEvent struct {
	Player_map []*PlayerInfo `sproto:"struct,0,array,name=Player_map"`

	Seat_state_map []*SeatState `sproto:"struct,1,array,name=Seat_state_map"`

	Player_cards_map *SeatCards `sproto:"struct,2,name=Player_cards_map"`

	Winlost_map []*Winlost `sproto:"struct,3,array,name=Winlost_map"`

	General_card int `sproto:"integer,4,name=General_card"`

	Used_cards []*UsedCardInfo `sproto:"struct,5,array,name=Used_cards"`

	History *GameEndEvent `sproto:"struct,6,name=History"`

	Seat_type *Seat_Type `sproto:"struct,7,name=Seat_type"`

	Next_bank_seat int `sproto:"integer,8,name=Next_bank_seat"`

	Deal_id string `sproto:"string,9,name=Deal_id"`

	Seat_count int `sproto:"integer,10,name=Seat_count"`
}

func (self *SeatStateEvent) String() string { return fmt.Sprintf("%+v", *self) }

type GameStartEvent struct {
	Cards []int `sproto:"integer,0,array,name=Cards"`

	Top_used_card *UsedCardInfo `sproto:"struct,1,name=Top_used_card"`

	General_card int `sproto:"integer,2,name=General_card"`

	Next_bank_seat int `sproto:"integer,3,name=Next_bank_seat"`

	Deal_id string `sproto:"string,4,name=Deal_id"`
}

func (self *GameStartEvent) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerDrawEvent struct {
	Seat int `sproto:"integer,1,name=Seat"`

	Card int `sproto:"integer,3,name=Card"`

	Player_id int `sproto:"integer,4,name=Player_id"`
}

func (self *PlayerDrawEvent) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerDiscardEvent struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Discard_card int `sproto:"integer,1,name=Discard_card"`

	Player_id int `sproto:"integer,2,name=Player_id"`
}

func (self *PlayerDiscardEvent) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerDropEvent struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Player_id int `sproto:"integer,1,name=Player_id"`

	Winlost int `sproto:"integer,2,name=Winlost"`
}

func (self *PlayerDropEvent) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerWinEvent struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Player_id int `sproto:"integer,1,name=Player_id"`

	Wincard int `sproto:"integer,2,name=Wincard"`
}

func (self *PlayerWinEvent) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerDeclareEvent struct {
	Winlost_map *Winlost `sproto:"struct,0,name=Winlost_map"`
}

func (self *PlayerDeclareEvent) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerSendGiftEvent struct {
	From_seat int `sproto:"integer,0,name=From_seat"`

	From_player_id int `sproto:"integer,1,name=From_player_id"`

	To_seat int `sproto:"integer,2,name=To_seat"`

	To_player_id int `sproto:"integer,3,name=To_player_id"`

	Gift_id int `sproto:"integer,4,name=Gift_id"`

	Gift_cost int `sproto:"integer,5,name=Gift_cost"`
}

func (self *PlayerSendGiftEvent) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerSendGiftReq struct {
	From_player_id int `sproto:"integer,0,name=From_player_id"`

	To_player_id int `sproto:"integer,1,name=To_player_id"`

	Gift_id int `sproto:"integer,2,name=Gift_id"`
}

func (self *PlayerSendGiftReq) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerSendGiftResp struct {
	From_player_id int `sproto:"integer,0,name=From_player_id"`

	To_player_id int `sproto:"integer,1,name=To_player_id"`

	Gift_id int `sproto:"integer,2,name=Gift_id"`

	Gift_cost int `sproto:"integer,3,name=Gift_cost"`
}

func (self *PlayerSendGiftResp) String() string { return fmt.Sprintf("%+v", *self) }

type Gift struct {
	Id int `sproto:"integer,0,name=Id"`

	Cost int `sproto:"integer,1,name=Cost"`
}

func (self *Gift) String() string { return fmt.Sprintf("%+v", *self) }

type SendGiftListEvent struct {
	Gift []*Gift `sproto:"struct,0,array,name=Gift"`
}

func (self *SendGiftListEvent) String() string { return fmt.Sprintf("%+v", *self) }

type PunishEvent struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Player_id int `sproto:"integer,1,name=Player_id"`

	Punish int `sproto:"integer,2,name=Punish"`
}

func (self *PunishEvent) String() string { return fmt.Sprintf("%+v", *self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*BalanceInfo)(nil)).Elem(),         // 3322160260
	reflect.TypeOf((*PlayerInfo)(nil)).Elem(),          // 1929887684
	reflect.TypeOf((*SeatState)(nil)).Elem(),           // 550931367
	reflect.TypeOf((*CardsGroup)(nil)).Elem(),          // 416499364
	reflect.TypeOf((*SeatCards)(nil)).Elem(),           // 2123146163
	reflect.TypeOf((*Winlost)(nil)).Elem(),             // 3870830425
	reflect.TypeOf((*TableBase)(nil)).Elem(),           // 2834792885
	reflect.TypeOf((*Table)(nil)).Elem(),               // 1619274330
	reflect.TypeOf((*QryDeskReq)(nil)).Elem(),          // 4207285648
	reflect.TypeOf((*QryDeskReply)(nil)).Elem(),        // 3002967342
	reflect.TypeOf((*DrawReq)(nil)).Elem(),             // 4060805644
	reflect.TypeOf((*DrawReply)(nil)).Elem(),           // 3912830041
	reflect.TypeOf((*DiscardReq)(nil)).Elem(),          // 3566326191
	reflect.TypeOf((*DiscardReply)(nil)).Elem(),        // 1433477343
	reflect.TypeOf((*WinReq)(nil)).Elem(),              // 778141670
	reflect.TypeOf((*WinReply)(nil)).Elem(),            // 1585091572
	reflect.TypeOf((*DeclareReq)(nil)).Elem(),          // 639016538
	reflect.TypeOf((*DeclareReply)(nil)).Elem(),        // 4227964925
	reflect.TypeOf((*DropReq)(nil)).Elem(),             // 291858475
	reflect.TypeOf((*DropReply)(nil)).Elem(),           // 390907442
	reflect.TypeOf((*DealInfo)(nil)).Elem(),            // 4239357180
	reflect.TypeOf((*GameEndEvent)(nil)).Elem(),        // 519507769
	reflect.TypeOf((*UsedCardInfo)(nil)).Elem(),        // 1228121655
	reflect.TypeOf((*Seat_Type)(nil)).Elem(),           // 2062188357
	reflect.TypeOf((*SeatStateEvent)(nil)).Elem(),      // 647579678
	reflect.TypeOf((*GameStartEvent)(nil)).Elem(),      // 938647597
	reflect.TypeOf((*PlayerDrawEvent)(nil)).Elem(),     // 310796500
	reflect.TypeOf((*PlayerDiscardEvent)(nil)).Elem(),  // 4189165416
	reflect.TypeOf((*PlayerDropEvent)(nil)).Elem(),     // 3975391935
	reflect.TypeOf((*PlayerWinEvent)(nil)).Elem(),      // 4169164777
	reflect.TypeOf((*PlayerDeclareEvent)(nil)).Elem(),  // 1354836042
	reflect.TypeOf((*PlayerSendGiftEvent)(nil)).Elem(), // 2635387406
	reflect.TypeOf((*PlayerSendGiftReq)(nil)).Elem(),   // 1459520330
	reflect.TypeOf((*PlayerSendGiftResp)(nil)).Elem(),  // 1808572771
	reflect.TypeOf((*Gift)(nil)).Elem(),                // 4042783085
	reflect.TypeOf((*SendGiftListEvent)(nil)).Elem(),   // 1457403392
	reflect.TypeOf((*PunishEvent)(nil)).Elem(),         // 232488596
}

var SProtoEnumValue = map[string]map[int32]string{}
