// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package gate

import (
	"reflect"

	"fmt"
)

type NetworkEvent struct {
	Type int `sproto:"integer,0,name=Type"`
}

func (self *NetworkEvent) String() string { return fmt.Sprintf("%+v", *self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*NetworkEvent)(nil)).Elem(), // 1706348731
}

var SProtoEnumValue = map[string]map[int32]string{}
