// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package desk

import (
	"reflect"

	"fmt"
)

type AddCdEvent struct {
	Id int `sproto:"integer,0,name=Id"`

	Cd_type int `sproto:"integer,1,name=Cd_type"`

	Cd_time int `sproto:"integer,2,name=Cd_time"`

	Player_id int `sproto:"integer,3,name=Player_id"`

	Seat int `sproto:"integer,4,name=Seat"`

	Begin_time int `sproto:"integer,5,name=Begin_time"`

	Turns int `sproto:"integer,6,name=Turns"`

	Drop int `sproto:"integer,7,name=Drop"`
}

func (self *AddCdEvent) String() string { return fmt.Sprintf("%+v", *self) }

type DelCdEvent struct {
	Id int `sproto:"integer,0,name=Id"`

	Cd_type int `sproto:"integer,1,name=Cd_type"`
}

func (self *DelCdEvent) String() string { return fmt.Sprintf("%+v", *self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*AddCdEvent)(nil)).Elem(), // 1806806412
	reflect.TypeOf((*DelCdEvent)(nil)).Elem(), // 1235727896
}

var SProtoEnumValue = map[string]map[int32]string{}
