// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package header

import (
	"reflect"

	"fmt"
)

type Package struct {
	Protoid int `sproto:"integer,0,name=Protoid"`

	Session int `sproto:"integer,1,name=Session"`

	Errorcode int `sproto:"integer,2,name=Errorcode"`

	Roomproxy string `sproto:"string,3,name=Roomproxy"`

	Datasize int `sproto:"integer,4,name=Datasize"`

	Response int `sproto:"integer,5,name=Response"`
}

func (self *Package) String() string { return fmt.Sprintf("%+v", *self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*Package)(nil)).Elem(), // 1920704843
}

var SProtoEnumValue = map[string]map[int32]string{}
