// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package player

import (
	"reflect"

	"fmt"
)

type BalanceInfo struct {
	Type int `sproto:"integer,0,name=Type"`

	Last_operate_time string `sproto:"string,1,name=Last_operate_time"`

	Balance int `sproto:"integer,2,name=Balance"`

	Player_id int `sproto:"integer,3,name=Player_id"`

	Sid int `sproto:"integer,4,name=Sid"`
}

func (self *BalanceInfo) String() string { return fmt.Sprintf("%+v", *self) }

type PlayerInfo struct {
	Seat int `sproto:"integer,0,name=Seat"`

	Player_id int `sproto:"integer,1,name=Player_id"`

	Nickname string `sproto:"string,2,name=Nickname"`

	Head_id int `sproto:"integer,3,name=Head_id"`

	Head_url string `sproto:"string,4,name=Head_url"`

	Sex int `sproto:"integer,5,name=Sex"`

	Balance_total int `sproto:"integer,6,name=Balance_total"`

	Balance []*BalanceInfo `sproto:"struct,7,array,name=Balance"`

	Avatar int `sproto:"integer,8,name=Avatar"`

	Fb_avatar string `sproto:"string,9,name=Fb_avatar"`
}

func (self *PlayerInfo) String() string { return fmt.Sprintf("%+v", *self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*BalanceInfo)(nil)).Elem(), // 3494811599
	reflect.TypeOf((*PlayerInfo)(nil)).Elem(),  // 1983155341
}

var SProtoEnumValue = map[string]map[int32]string{}
