// Generated by github.com/davyxu/gosproto/sprotogen
// DO NOT EDIT!

package room

import (
	"reflect"

	"fmt"
)

type EnterRoomReply struct {
	Room_id int `sproto:"integer,0,name=Room_id"`

	Roomproxy string `sproto:"string,1,name=Roomproxy"`

	Room_type int `sproto:"integer,2,name=Room_type"`
}

func (self *EnterRoomReply) String() string { return fmt.Sprintf("%+v", *self) }

type ExitRoomReply struct {
}

func (self *ExitRoomReply) String() string { return fmt.Sprintf("%+v", *self) }

type GroupReq struct {
	Game_id int `sproto:"integer,0,name=Game_id"`
}

func (self *GroupReq) String() string { return fmt.Sprintf("%+v", *self) }

type GroupReply struct {
	Game_id int `sproto:"integer,0,name=Game_id"`

	Point_value int `sproto:"integer,1,name=Point_value"`

	Desk_id int `sproto:"integer,2,name=Desk_id"`

	Desk_config []int `sproto:"integer,3,array,name=Desk_config"`
}

func (self *GroupReply) String() string { return fmt.Sprintf("%+v", *self) }

var SProtoStructs = []reflect.Type{

	reflect.TypeOf((*EnterRoomReply)(nil)).Elem(), // 3323271565
	reflect.TypeOf((*ExitRoomReply)(nil)).Elem(),  // 1958668822
	reflect.TypeOf((*GroupReq)(nil)).Elem(),       // 2686735698
	reflect.TypeOf((*GroupReply)(nil)).Elem(),     // 298854940
}

var SProtoEnumValue = map[string]map[int32]string{}
